### ISSUE TITLE
Migrate to Heptagram 1st party API

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot-Project/bot#297]
List of things to migrate completely to our first-party API.

- [ ] Migrate commands cat, encouragement, hug, joke, movie qoute, and word definition commands to use API
- [ ] Update ping command to include API Ping
- [ ] Update API Info Command

**Comment by j-dogcoder** [comment]
**LOCKED DUE TO STAFF ONLY. STAFF AND NECESSARY CONTRIBUTORS SHOULD HAVE ACCESS.**

**Comment by j-dogcoder** [comment]
Hey @Vyvy-vi, any progress on this?

**Comment by Vyvy-vi** [comment]
Yes, I'll do this today.

We use axios, right?

**Comment by j-dogcoder** [comment]
I think so. I am open to changing that though
