### ISSUE TITLE
[FEAT] - Add weather command

### ISSUE THREAD

**Issue by Kevan-Y** [Heptagram-Bot-Project/bot#370]
### What feature would you like to see?

- Add weather command.

Calling the command either 
```
!weather city,country 
!weather city
```
The embed can look like this
![image](https://user-images.githubusercontent.com/58233223/140209181-9af54abb-a2ca-419e-9e09-825e4123c78f.png)

Data from https://openweathermap.org/

**Comment by Kevan-Y** [comment]
If there is no issue I will work on that.

**Comment by j-dogcoder** [comment]
Go for it!

**Comment by apoorvcodes** [comment]
are you working on it?

**Comment by Kevan-Y** [comment]
@apoorvcodes, yes I had some issue with the config file. I was waiting for @j-dogcoder to rework some of the config.

**Comment by apoorvcodes** [comment]
so the issue is fixed?

**Comment by Kevan-Y** [comment]
I have issue setting up the bot locally, is it possible to have some help?

**Comment by j-dogcoder** [comment]
Check in with @apoorvcodes

**Comment by apoorvcodes** [comment]
what are the issues

**Comment by apoorvcodes** [comment]
just lemme know and ill see to it
