### ISSUE TITLE
[FEAT] -  automatically publishes messages sent in announcement channels

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot-Project/bot#384]
### What feature would you like to see?

like [https://github.com/Benricheson101/Publisher](https://github.com/Benricheson101/Publisher)

**Comment by MoOaAaa** [comment]
.take

**Comment by j-dogcoder** [comment]
Thanks for claiming this!


As an internal note to the team, this needs to be added to the list of configurables
